# Generated by Django 4.2.2 on 2023-06-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_teacherinfo_stuinfo_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StuInfo',
        ),
        migrations.DeleteModel(
            name='TeacherInfo',
        ),
    ]
