# Generated by Django 4.2.2 on 2023-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0003_delete_stuinfo_delete_teacherinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=64)),
                ('stuid', models.CharField(max_length=32)),
                ('stuschool', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaname', models.CharField(max_length=64)),
                ('teaid', models.CharField(max_length=32)),
                ('teaschool', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
