# Generated by Django 4.2.2 on 2023-06-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_essayquestion_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsOptionQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuAns', models.CharField(max_length=1)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('optQid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.questionoption')),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.stuinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AnsEssayQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuAns', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('essQid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.essayquestion')),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.stuinfo')),
            ],
        ),
    ]
